services:
  service1:
    build:
      dockerfile: Dockerfile
      context: service-1
    ports:
      - 3000:18888
    networks:
      - unify
  service2:
    build:
      dockerfile: Dockerfile
      context: service-2
    ports:
      - 3001:18888
    networks:
      - net1
      - unify
  nginx:
    build:
      dockerfile: Dockerfile
      context: nginx
    ports:
      - 80:80
    networks:
      - net1
networks:
  net1:
